---
deployment:
  tasks:
    - /usr/bin/rsync -av --progress public/ $HOME/public_html/
    - /bin/cp public/.htaccess $HOME/public_html/.htaccess
    - /bin/cp public/index.php $HOME/public_html/index.php
